// use js to create a snake, water, gun game . The game should ask you to enter S, W and G. The computer should be able to randomly generate S, W and G and declare win or loss using alert functions...
// if required use confirm and prompt...

